package com.circustar.mybatis_accessor.common;

public class MvcEnhanceConstants {
    public final static String MYBATIS_ENHANCE_JOIN_TABLE = "__MYBATIS_ENHANCE_JOIN_TABLE";
    public final static String MYBATIS_ENHANCE_JOIN_COLUMNS = "__MYBATIS_ENHANCE_JOIN_COLUMNS";

    public final static String UPDATE_STRATEGY_UPDATE_CHILDREN_ONLY = "_UPDATE_STRATEGY_UPDATE_CHILDREN_ONLY";
    public final static String UPDATE_STRATEGY_UPDATE_CHILDREN_LIST = "_UPDATE_STRATEGY_UPDATE_CHILDREN_LIST";
    public final static String UPDATE_STRATEGY_INCLUDE_ALL_CHILDREN = "_UPDATE_STRATEGY_INCLUDE_ALL_CHILDREN";
    public final static String UPDATE_STRATEGY_DELETE_AND_INSERT = "_UPDATE_STRATEGY_DELETE_AND_INSERT";
    public final static String UPDATE_STRATEGY_INSERT_PARENTS = "UPDATE_STRATEGY_INSERT_PARENTS";
}
