package com.circustar.mvcenhance.utils;

public class MvcEnhanceConstants {
    public final static String MYBATIS_ENHANCE_JOIN_TABLE = "__MYBATIS_ENHANCE_JOIN_TABLE";
    public final static String MYBATIS_ENHANCE_JOIN_COLUMNS = "__MYBATIS_ENHANCE_JOIN_COLUMNS";

    public final static String UPDATE_STRATEGY_TARGET_LIST = "UPDATE_STRATEGY_TARGET_LIST";
    public final static String UPDATE_STRATEGY_UPDATE_CHILDREN_ONLY = "UPDATE_STRATEGY_UPDATE_CHILDREN_ONLY";
    public final static String UPDATE_STRATEGY_INSERT_ALL_CHILDREN = "UPDATE_STRATEGY_INSERT_ALL_CHILDREN";
    public final static String UPDATE_STRATEGY_DELETE_AND_INSERT = "UPDATE_STRATEGY_DELETE_AND_INSERT";
    public final static String UPDATE_STRATEGY_PHYSIC_DELETE = "UPDATE_STRATEGY_PHYSIC_DELETE";
}
